export declare function cacheUserData(jid: string, data: { username?: string; [key: string]: any }): void;
export declare function getCachedUserData(jid: string): { username?: string; jid?: string; source?: string; _cachedAt?: number } | null;
export declare function extractUsernameFromContact(contact: any): string | null;
export declare function extractFullContactData(contact: any): any;
export declare function extractUsernameFromMessage(message: any): string | null;
export declare function extractFullMessageMetadata(message: any): any;
export declare function extractUsernameFromGroupParticipant(participant: any): string | null;
export declare function extractFullParticipantData(participant: any): any;
export declare function resolveUsername(jid: string, options: {
    sock?: any;
    groupMetadata?: any;
    contacts?: Record<string, any>;
    lidMapping?: any;
}): Promise<string | null>;
export declare function buildUserMapFromMessages(messages: any[], options?: { sock?: any }): Map<string, { username: string | null; source: string; fullMetadata?: any }>;
export declare function enrichUserMap(userMap: Map<string, { username: string | null; source: string; fullMetadata?: any }>, options: { contacts?: Record<string, any>; groupMetadata?: any; sock?: any }): Map<string, { username: string | null; source: string; jid?: string; fullContactData?: any; fullParticipantData?: any }>;
export declare function getUsername(jid: string, options?: { userMap?: Map<string, { username: string | null; source: string }> }): string | null;
export declare function getDisplayName(jid: string, options?: { userMap?: Map<string, { username: string | null; source: string }>; groupMetadata?: any }): string;
export declare function getFullUserProfile(jid: string, options?: { userMap?: Map<string, any>; groupMetadata?: any; contacts?: Record<string, any>; sock?: any }): any;
export declare const userDataCache: Map<string, any>;